version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: videgrenier-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db


  db:
    image: mysql:8
    container_name: videgrenier-db
    restart: always
    env_file:
      - dev.env
    environment:
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
      MYSQL_ROOT_PASSWORD: 653rag9T
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data:
